version: '3'

services:
  app:
    build: .     
    depends_on:
      - cassandra

  cassandra:
    image: cassandra:latest
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
